ARG NODE_VERSION=22.17.1
FROM node:${NODE_VERSION}-alpine

WORKDIR /server

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

COPY . .

EXPOSE 3000

CMD npm run dev